// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmG8Kw6GszgEj9y-OjJ8Si1Kn_IjScSl4',
    appId: '1:609637842223:web:1dc631278e259b301c75da',
    messagingSenderId: '609637842223',
    projectId: 'almaworks-b9a2e',
    authDomain: 'almaworks-b9a2e.firebaseapp.com',
    storageBucket: 'almaworks-b9a2e.firebasestorage.app',
    measurementId: 'G-GJ5GL0C299',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXAcu_XmC4hB6OSv8iPE9r-eA1TLhQO5g',
    appId: '1:609637842223:android:160c47e87f5ea42e1c75da',
    messagingSenderId: '609637842223',
    projectId: 'almaworks-b9a2e',
    storageBucket: 'almaworks-b9a2e.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmG8Kw6GszgEj9y-OjJ8Si1Kn_IjScSl4',
    appId: '1:609637842223:web:d6670e9625fd936f1c75da',
    messagingSenderId: '609637842223',
    projectId: 'almaworks-b9a2e',
    authDomain: 'almaworks-b9a2e.firebaseapp.com',
    storageBucket: 'almaworks-b9a2e.firebasestorage.app',
    measurementId: 'G-794S5DCX6R',
  );
}
